name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install Swag CLI 
      run: go get -u github.com/swaggo/swag/cmd/swag

    - name: Generate Swagger documentation
      run: swag init
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
